---

- hosts: localhost
  become: yes
  become_method: sudo

  tasks:
    - name: refresh apt cache
      apt:
        update_cache: true
  
    - name: install git latest version
      apt: 
        name: git
        state: latest

    - name: install vim latest version
      apt: 
        name: vim
        state: latest
